from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class FileReport(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, path=None, code_time=None, save_number=None, lines_modified=None):  # noqa: E501
        """FileReport - a model defined in OpenAPI

        :param path: The path of this FileReport.  # noqa: E501
        :type path: str
        :param code_time: The code_time of this FileReport.  # noqa: E501
        :type code_time: int
        :param save_number: The save_number of this FileReport.  # noqa: E501
        :type save_number: int
        :param lines_modified: The lines_modified of this FileReport.  # noqa: E501
        :type lines_modified: object
        """
        self.openapi_types = {
            'path': str,
            'code_time': int,
            'save_number': int,
            'lines_modified': object
        }

        self.attribute_map = {
            'path': 'path',
            'code_time': 'codeTime',
            'save_number': 'saveNumber',
            'lines_modified': 'linesModified'
        }

        self._path = path
        self._code_time = code_time
        self._save_number = save_number
        self._lines_modified = lines_modified

    @classmethod
    def from_dict(cls, dikt) -> 'FileReport':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FileReport of this FileReport.  # noqa: E501
        :rtype: FileReport
        """
        return util.deserialize_model(dikt, cls)

    @property
    def path(self) -> str:
        """Gets the path of this FileReport.

        Path to file relative to project root  # noqa: E501

        :return: The path of this FileReport.
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path: str):
        """Sets the path of this FileReport.

        Path to file relative to project root  # noqa: E501

        :param path: The path of this FileReport.
        :type path: str
        """

        self._path = path

    @property
    def code_time(self) -> int:
        """Gets the code_time of this FileReport.

        Time spent coding this file in milliseconds  # noqa: E501

        :return: The code_time of this FileReport.
        :rtype: int
        """
        return self._code_time

    @code_time.setter
    def code_time(self, code_time: int):
        """Sets the code_time of this FileReport.

        Time spent coding this file in milliseconds  # noqa: E501

        :param code_time: The code_time of this FileReport.
        :type code_time: int
        """

        self._code_time = code_time

    @property
    def save_number(self) -> int:
        """Gets the save_number of this FileReport.

        Total number of times this file was saved  # noqa: E501

        :return: The save_number of this FileReport.
        :rtype: int
        """
        return self._save_number

    @save_number.setter
    def save_number(self, save_number: int):
        """Sets the save_number of this FileReport.

        Total number of times this file was saved  # noqa: E501

        :param save_number: The save_number of this FileReport.
        :type save_number: int
        """

        self._save_number = save_number

    @property
    def lines_modified(self) -> object:
        """Gets the lines_modified of this FileReport.


        :return: The lines_modified of this FileReport.
        :rtype: object
        """
        return self._lines_modified

    @lines_modified.setter
    def lines_modified(self, lines_modified: object):
        """Sets the lines_modified of this FileReport.


        :param lines_modified: The lines_modified of this FileReport.
        :type lines_modified: object
        """

        self._lines_modified = lines_modified
