services:
  dspdavscp:
    image: ghcr.io/dspdavscp/dspdavscp-server
    build:
      dockerfile: server/docker/Dockerfile
      context: ../..
      target: deploy
    ports:
      - 80:80
    environment:
      DSPDAVSCP_PORT: 80
      DSPDAVSCP_DEBUG: False
    network_mode: host
