name: PUBLISH

on:
  push:
    paths:
      - 'plugin/**'
      - 'DSPDAVSCPAPI.yaml'
      - '.github/workflows/publish.yaml'

concurrency:
  group: REPORT-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  publish-extension:
    name: Publish extension
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install
      working-directory: plugin
      run: npm install

    - name: Copy README
      run: cp README.md plugin/README.md

    - name: Package VS Code extension
      id: package
      uses: nhedger/package-vscode-extension@v1
      with:
        extensionPath: plugin

    - name: Update Release
      if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags') }}
      uses: johnwbyrd/update-release@v1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        release: VSIX package latest
        files: ${{ steps.package.outputs.packagePath }}

  publish-server:
    name: Build server container
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/dspdavscp-server
          tags: |
            type=sha
            type=schedule
            type=ref,event=pr
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          file: server/docker/Dockerfile
          target: deploy
          push: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
